// flow-typed signature: fe9c4064762d6bca979c11642bebc666
// flow-typed version: <<STUB>>/dotenv.macro_v^1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv.macro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv.macro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv.macro/lib/index' {
  declare module.exports: any;
}

declare module 'dotenv.macro/lib/macro' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv.macro/lib/index.js' {
  declare module.exports: $Exports<'dotenv.macro/lib/index'>;
}
declare module 'dotenv.macro/lib/macro.js' {
  declare module.exports: $Exports<'dotenv.macro/lib/macro'>;
}
