// flow-typed signature: 4786c7354e32e8ed8db3415bc3801b0a
// flow-typed version: <<STUB>>/microrouter_v^3.1.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'microrouter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'microrouter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'microrouter/dist/lib/index' {
  declare module.exports: any;
}

declare module 'microrouter/dist/utils/index' {
  declare module.exports: any;
}

declare module 'microrouter/src/lib/index' {
  declare module.exports: any;
}

declare module 'microrouter/src/lib/index.test' {
  declare module.exports: any;
}

declare module 'microrouter/src/utils/index' {
  declare module.exports: any;
}

declare module 'microrouter/src/utils/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'microrouter/dist/lib/index.js' {
  declare module.exports: $Exports<'microrouter/dist/lib/index'>;
}
declare module 'microrouter/dist/utils/index.js' {
  declare module.exports: $Exports<'microrouter/dist/utils/index'>;
}
declare module 'microrouter/src/lib/index.js' {
  declare module.exports: $Exports<'microrouter/src/lib/index'>;
}
declare module 'microrouter/src/lib/index.test.js' {
  declare module.exports: $Exports<'microrouter/src/lib/index.test'>;
}
declare module 'microrouter/src/utils/index.js' {
  declare module.exports: $Exports<'microrouter/src/utils/index'>;
}
declare module 'microrouter/src/utils/index.test.js' {
  declare module.exports: $Exports<'microrouter/src/utils/index.test'>;
}
