// flow-typed signature: 4bd25dc346306a3c13a5459faeef2723
// flow-typed version: <<STUB>>/micro-ratelimit_v^0.3.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-ratelimit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-ratelimit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro-ratelimit/lib/memory-store' {
  declare module.exports: any;
}

declare module 'micro-ratelimit/lib/rate-limit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro-ratelimit/lib/memory-store.js' {
  declare module.exports: $Exports<'micro-ratelimit/lib/memory-store'>;
}
declare module 'micro-ratelimit/lib/rate-limit.js' {
  declare module.exports: $Exports<'micro-ratelimit/lib/rate-limit'>;
}
