// flow-typed signature: 9920c1ceb1d9a79aad1a52a8d847b183
// flow-typed version: <<STUB>>/micro-compress_v1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-compress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-compress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro-compress/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro-compress/src/index.js' {
  declare module.exports: $Exports<'micro-compress/src/index'>;
}
