// flow-typed signature: 3873cf810c56ad4d589b044d2d415687
// flow-typed version: <<STUB>>/react-native-router-flux_v^4.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-router-flux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-router-flux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-router-flux/__tests__/scenes.test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/ReduxExample/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/ReduxExample/index.android' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/ReduxExample/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/ReduxExample/src/a-reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/ReduxExample/src/app' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/ReduxExample/src/home' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/ReduxExample/src/page' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/createStackNavigatorHOC' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/createTabNavigatorHOC' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Lightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/LightboxRenderer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Modal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/navigationStore' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/OverlayRenderer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/pathParser' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Stack' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/State' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Tabs' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-router-flux/__tests__/scenes.test.js' {
  declare module.exports: $Exports<'react-native-router-flux/__tests__/scenes.test'>;
}
declare module 'react-native-router-flux/babel.config.js' {
  declare module.exports: $Exports<'react-native-router-flux/babel.config'>;
}
declare module 'react-native-router-flux/ReduxExample/babel.config.js' {
  declare module.exports: $Exports<'react-native-router-flux/ReduxExample/babel.config'>;
}
declare module 'react-native-router-flux/ReduxExample/index.android.js' {
  declare module.exports: $Exports<'react-native-router-flux/ReduxExample/index.android'>;
}
declare module 'react-native-router-flux/ReduxExample/index.ios.js' {
  declare module.exports: $Exports<'react-native-router-flux/ReduxExample/index.ios'>;
}
declare module 'react-native-router-flux/ReduxExample/src/a-reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/ReduxExample/src/a-reducer'>;
}
declare module 'react-native-router-flux/ReduxExample/src/app.js' {
  declare module.exports: $Exports<'react-native-router-flux/ReduxExample/src/app'>;
}
declare module 'react-native-router-flux/ReduxExample/src/home.js' {
  declare module.exports: $Exports<'react-native-router-flux/ReduxExample/src/home'>;
}
declare module 'react-native-router-flux/ReduxExample/src/page.js' {
  declare module.exports: $Exports<'react-native-router-flux/ReduxExample/src/page'>;
}
declare module 'react-native-router-flux/src/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/ActionConst'>;
}
declare module 'react-native-router-flux/src/createStackNavigatorHOC.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/createStackNavigatorHOC'>;
}
declare module 'react-native-router-flux/src/createTabNavigatorHOC.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/createTabNavigatorHOC'>;
}
declare module 'react-native-router-flux/src/Drawer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Drawer'>;
}
declare module 'react-native-router-flux/src/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/index'>;
}
declare module 'react-native-router-flux/src/Lightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Lightbox'>;
}
declare module 'react-native-router-flux/src/LightboxRenderer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/LightboxRenderer'>;
}
declare module 'react-native-router-flux/src/Modal.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Modal'>;
}
declare module 'react-native-router-flux/src/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/NavBar'>;
}
declare module 'react-native-router-flux/src/navigationStore.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/navigationStore'>;
}
declare module 'react-native-router-flux/src/Overlay.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Overlay'>;
}
declare module 'react-native-router-flux/src/OverlayRenderer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/OverlayRenderer'>;
}
declare module 'react-native-router-flux/src/pathParser.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/pathParser'>;
}
declare module 'react-native-router-flux/src/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Reducer'>;
}
declare module 'react-native-router-flux/src/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Router'>;
}
declare module 'react-native-router-flux/src/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Scene'>;
}
declare module 'react-native-router-flux/src/Stack.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Stack'>;
}
declare module 'react-native-router-flux/src/State.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/State'>;
}
declare module 'react-native-router-flux/src/Tabs.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Tabs'>;
}
declare module 'react-native-router-flux/src/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Util'>;
}
declare module 'react-native-router-flux/test/setup.js' {
  declare module.exports: $Exports<'react-native-router-flux/test/setup'>;
}
