// flow-typed signature: 8adc254e3a185baa1c5b68af6fb7068f
// flow-typed version: <<STUB>>/test-listen_v^1.1.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'test-listen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'test-listen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'test-listen/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'test-listen/index' {
  declare module.exports: $Exports<'test-listen'>;
}
declare module 'test-listen/index.js' {
  declare module.exports: $Exports<'test-listen'>;
}
declare module 'test-listen/test/index.js' {
  declare module.exports: $Exports<'test-listen/test/index'>;
}
